AWSTemplateFormatVersion: 2010-09-09
Resources:
  ImageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: s1108900-table
      AttributeDefinitions:
        - AttributeName: "s1108900"
          AttributeType: "S"
        - AttributeName: "CloudPlatformDevelopment"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "s1108900"
          KeyType: "HASH"
        - AttributeName: "CloudPlatformDevelopment"
          KeyType: "RANGE"
      TimeToLiveSpecification:
        AttributeName: "ExpirationTime"
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: "10"
        WriteCapacityUnits: "5"
  SQSQueuePolicy:
    Type: "AWS::SQS::Queue"
    Properties:
      DelaySeconds: 100
      KmsDataKeyReusePeriodSeconds: 86400
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 345600
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 30
      