AWSTemplateFormatVersion: 2010-09-09
Resources:
  ImageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: s1108900-table
      AttributeDefinitions:
        - AttributeName: "Image"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Image"
          KeyType: "HASH"
      TimeToLiveSpecification:
        AttributeName: "ExpirationTime"
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
  
  SQSQueueLabels:
    Type: "AWS::SQS::Queue"
    Properties:
      DelaySeconds: 100
      KmsDataKeyReusePeriodSeconds: 86400
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 345600
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 30